import { describe, expect, test } from "bun:test";

// web-page-ext.cjs is generated by build-ext.mjs — requires `pnpm build` first
const ext = require("../dist/web-page-ext.cjs") as {
  WEB_CLIENT_CSS: string;
  WEB_CLIENT_JS: string;
  WEB_CLIENT_HTML_SHELL_TEMPLATE: string;
};

describe("web-page-ext exports", () => {
  test("WEB_CLIENT_CSS is non-empty and contains key selectors", () => {
    expect(ext.WEB_CLIENT_CSS.length).toBeGreaterThan(10000);
    expect(ext.WEB_CLIENT_CSS).toContain(".aup-view");
    expect(ext.WEB_CLIENT_CSS).toContain("--color-accent");
  });

  test("WEB_CLIENT_JS is non-empty and parses as valid JS", () => {
    expect(ext.WEB_CLIENT_JS.length).toBeGreaterThan(10000);
    expect(() => new Function(ext.WEB_CLIENT_JS)).not.toThrow();
  });

  test("WEB_CLIENT_JS is minified (smaller than source)", () => {
    // Unminified JS is ~487KB; minified should be < 300KB
    expect(ext.WEB_CLIENT_JS.length).toBeLessThan(300 * 1024);
  });

  test("HTML shell template contains asset hash placeholder", () => {
    expect(ext.WEB_CLIENT_HTML_SHELL_TEMPLATE).toContain("/aup.css?v=__ASSET_HASH__");
    expect(ext.WEB_CLIENT_HTML_SHELL_TEMPLATE).toContain("/aup.js?v=__ASSET_HASH__");
  });

  test("HTML shell does NOT contain main inline CSS or JS", () => {
    // Main CSS selectors and JS function names should NOT be in the shell
    expect(ext.WEB_CLIENT_HTML_SHELL_TEMPLATE).not.toContain(".aup-view");
    expect(ext.WEB_CLIENT_HTML_SHELL_TEMPLATE).not.toContain("renderMessage");
  });

  test("HTML shell contains early WS script", () => {
    expect(ext.WEB_CLIENT_HTML_SHELL_TEMPLATE).toContain("_earlyWs");
  });

  test("HTML shell contains CDN preconnect", () => {
    expect(ext.WEB_CLIENT_HTML_SHELL_TEMPLATE).toContain("cdn.jsdelivr.net");
  });
});
