/**
 * AFS Basic Example
 *
 * Demonstrates core AFS operations: mount, list, read, write, search.
 *
 * Run:  bun examples/basic/index.ts
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { AFS } from "@aigne/afs";
import { AFSFS } from "@aigne/afs-fs";
import { AFSJSON } from "@aigne/afs-json";

// Create a temp directory with some sample files
const sampleDir = join(tmpdir(), `afs-example-${Date.now()}`);
mkdirSync(join(sampleDir, "src"), { recursive: true });
writeFileSync(join(sampleDir, "README.md"), "# My Project\n\nA sample project.\n");
writeFileSync(
  join(sampleDir, "src/index.ts"),
  "export function hello() {\n  return 'Hello from AFS!';\n}\n",
);
writeFileSync(
  join(sampleDir, "src/utils.ts"),
  "// TODO: add utility functions\nexport const VERSION = '1.0.0';\n",
);
writeFileSync(
  join(sampleDir, "config.json"),
  JSON.stringify(
    { name: "my-app", version: "1.0.0", features: { auth: true, api: true } },
    null,
    2,
  ),
);

console.log("AFS Basic Example\n");

// ── 1. Create AFS and mount providers ──

const afs = new AFS();

// Mount local filesystem
await afs.mount(
  new AFSFS({ localPath: sampleDir, description: "Sample project files" }),
  "/project",
);

// Mount a JSON file as a navigable tree
await afs.mount(
  new AFSJSON({ localPath: join(sampleDir, "config.json"), description: "App config" }),
  "/config",
);

console.log("Mounted providers:");
for (const m of afs.getMounts()) {
  console.log(`  ${m.path} → ${m.module.name}`);
}

// ── 2. List files ──

console.log("\n--- List /project ---");
const { data: files } = await afs.list("/project");
for (const f of files) {
  const icon = f.type === "directory" ? "📁" : "📄";
  console.log(`  ${icon} ${f.id || f.name}`);
}

console.log("\n--- List /project/src ---");
const { data: srcFiles } = await afs.list("/project/src");
for (const f of srcFiles) {
  console.log(`  📄 ${f.id || f.name}  (${f.meta?.size ?? "?"} bytes)`);
}

// ── 3. Read a file ──

console.log("\n--- Read /project/README.md ---");
const readme = await afs.read("/project/README.md");
console.log(readme.data?.content ?? readme.data);

// ── 4. Navigate JSON as a tree ──

console.log("--- Navigate /config (JSON as directories) ---");
const { data: configEntries } = await afs.list("/config");
for (const e of configEntries) {
  const icon = e.type === "directory" ? "📁" : "📄";
  console.log(`  ${icon} ${e.id || e.name}`);
}

const appName = await afs.read("/config/name");
console.log(`  config.name = ${JSON.stringify(appName.data?.content ?? appName.data)}`);

const features = await afs.list("/config/features");
console.log(`  config.features → ${features.data.map((f: any) => f.id || f.name).join(", ")}`);

// ── 5. Search ──

console.log("\n--- Search for 'TODO' in /project ---");
const results = await afs.search("/project", "TODO");
for (const r of results.data) {
  console.log(`  ${r.path || r.id}: match found`);
}

// ── 6. Write a file ──

console.log("\n--- Write /project/output.txt ---");
await afs.write("/project/output.txt", { content: "Generated by AFS example" });
const written = await afs.read("/project/output.txt");
console.log(`  Written: ${written.data?.content ?? written.data}`);

// ── 7. Stat (metadata without content) ──

console.log("\n--- Stat /project/src/index.ts ---");
const stat = await afs.stat("/project/src/index.ts");
console.log(`  size: ${stat.data?.meta?.size ?? stat.data?.size ?? "?"} bytes`);

console.log("\nDone!");
